#!/usr/bin/env bash

if [ $# -lt 2 ]; then
  # >&2 echo "Usage: $0 <repository>  <directory> [path_to_subdirectory]"
  >&2 echo "Usage: $0 <repository> [path_to_subdirectory]"
  exit 1
fi

CURRENT_DIR=$PWD

REPOSITORY=$1 # the repository to clone
# DIRECTORY=$2 # the directory to clone into
SUB_DIRECTORIES=( "${@:2}") # an array of directories


if git clone --no-checkout "$REPOSITORY" ; then 

  DIRECTORY=$(basename "$_" "$GIT_DIR")
  cd "$DIRECTORY" || exit 1
  git sparse-checkout init

  for SUBDIR in "${SUB_DIRECTORIES[@]}"
  do
    SP_FREE_SUBDIR=$(printf '%s' "$SUBDIR" | sed "s|^/||" | sed "s|/$||")
    if ! git ls-tree -r -d --name-only HEAD | grep -x -q "$SP_FREE_SUBDIR"; then
      echo could not find '"'"$SP_FREE_SUBDIR"'"' in the tree , quiting
      rm -rf "$CURRENT_DIR"/"$DIRECTORY"
      exit 1
    fi
  done

  git sparse-checkout set "${SUB_DIRECTORIES[@]}"

  echo "All done";

fi

exit 0